---
title: "Reading training"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme:
      version: 4
      bootswatch: cosmo
    css: styles.css
    source_code: embed
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Load libraries   ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# library("here")
library("data.table")
library("lubridate")
library("glue")
library("readr")

url_base <- "https://github.com/randrescastaneda/reading-words/raw/main/static"
source("R/utils.R")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# set up   ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


words <- c(letters, LETTERS)
words <- c("Dios", "Jesús", "carro", "perro", "mamá", "hola", "chao", "usted", "tú", "él", "ella", "amor", "caro", "sí", "no", "ahora", "después", "cuando", "está", "esta", "soy", "es", "ya", "papá", "español")


languages <- read_lines(glue("{url_base}/languages"))

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# functions   ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```


Sidebar {.sidebar  data-width=350} 
-----------------------------------------------------------------------

### Settings

```{r settings}
  actionButton('start','Start')
  actionButton('stop','Stop')
  actionButton('reset','Reset')
  sliderInput("lnth", "Session length (minutes):", 
              min = .5, max = 5, step = .5, value = 1)
  numericInput('seconds','Seconds:',value=5,min=0,max=99999,step=1)
  hr()
  selectInput(
        "lang",
        label = "Select your language",
        choices = c(empty = "", languages),
        selected = "",
        multiple = FALSE
      )
  selectInput(
        "tt",
        label = "Training type",
        choices = c(empty = ""),
        selected = "",
        multiple = FALSE
      )
  selectInput(
        "gr",
        label = "Training groups (empty for all groups)",
        choices = c(empty = ""),
        selected = "",
        multiple = TRUE
      )
```



```{r udpate-settings}

# update training type based on language
  tts <- reactive({
    training_type(input$lang)
  })

  observeEvent(input$lang, {
    
    updateSelectInput(
      session,
      "tt",
      choices = c(empty = "", tts()),
      selected = ""
    )
  })

# update training groups based on training type
  ttf <- reactive({
    if (input$lang == ""  | input$tt == "") {
      ttf <- NULL
    }  else {
      ttf <- training_type_file(lang = input$lang, 
                                tt   = input$tt, 
                                url_base)
    }
    return(ttf)
    
  })
  
  observeEvent(input$tt, {
    
    if(is.null(ttf())) {
      groups <- c(empty = "")
    } else {
      groups <- c("all", ttf()[, unique(group)])
    }
    
      
    updateSelectInput(
      session,
      "gr",
      choices = groups,
      selected = "all"
    )
  })



```

Column {data-width=900}
-----------------------------------------------------------------------


```{r}
  # Initialize the timer, 5 seconds, not active.
  s_timer <- reactiveVal(60)  # session timer
  timer   <- reactiveVal(5)   # reading timer
  active  <- reactiveVal(FALSE)

  # observer that invalidates every second. If timer is active, decrease by one.
  observe({
    invalidateLater(1000, session)
    isolate({
      # start counting down
      if(active()) {

        timer(timer()-1)
        s_timer(s_timer()-1)
        
        if(timer()<1) {
          timer(input$seconds)
        }
        
        # message if session time is up
        if(s_timer()<1) {
          active(FALSE)
          showModal(modalDialog(
            title = "Time's up!",
            "Let's go for another session"
          ))
        }
        
        
      }
    })
  })

  # observers for actionbuttons
  observeEvent(input$start, {
    timer(input$seconds)
    s_timer(input$lnth*60)
    active(TRUE)
    })
  observeEvent(input$stop, {active(FALSE)})
  observeEvent(input$reset, {
    timer(input$seconds)
    s_timer(input$lnth*60)
    })

```


```{r timeleft}
# Output the time left.
  textOutput('timeleft')
  renderText({
    paste("Time left: ", seconds_to_period(s_timer()))
  })
  
```


```{r word}
words <- reactive({
  if ("all"  %in% input$gr) {
    dt <- copy(ttf())
  } else {
    dt <- ttf()[group  %in% input$gr]
  }
  
  words <- dt[, to_read]
  return(words)
})

textOutput('word')
output$word <-   renderText({
    invalidateLater(input$seconds*1000)
    if(active()) {
      sample(words(), 1)
    }
  })

```
